# Generated by Django 5.1.1 on 2024-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNo', models.IntegerField(max_length=42)),
                ('EmpName', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(max_length=50)),
            ],
        ),
    ]
